//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marriage
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int ToPersonId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual PersonInfo PersonInfo { get; set; }
        public virtual PersonInfo PersonInfo1 { get; set; }
    }
}
