//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community
{
    using System;
    using System.Collections.Generic;
    
    public partial class MassMrgGift
    {
        public int Id { get; set; }
        public int MassMrgId { get; set; }
        public int GiftTo { get; set; }
        public int GiftFrom { get; set; }
    
        public virtual MassMrg MassMrg { get; set; }
        public virtual PersonInfo PersonInfo { get; set; }
        public virtual MassMrgReg MassMrgReg { get; set; }
    }
}
