//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community
{
    using System;
    using System.Collections.Generic;
    
    public partial class MassMrgExpenditure
    {
        public int Id { get; set; }
        public int MassMrgId { get; set; }
        public string Amount { get; set; }
        public string ForDiscription { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual MassMrg MassMrg { get; set; }
    }
}
