//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community
{
    using System;
    using System.Collections.Generic;
    
    public partial class MassMrgReg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MassMrgReg()
        {
            this.MassMrgGifts = new HashSet<MassMrgGift>();
        }
    
        public int Id { get; set; }
        public int MassMrgId { get; set; }
        public int GroomId { get; set; }
        public int BrideId { get; set; }
        public string Documents { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual MassMrg MassMrg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MassMrgGift> MassMrgGifts { get; set; }
        public virtual PersonInfo PersonInfo { get; set; }
        public virtual PersonInfo PersonInfo1 { get; set; }
    }
}
