//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherPersonInfo
    {
        public int Id { get; set; }
        public string Hobbies { get; set; }
        public string LeanguageSpeak { get; set; }
        public string Achivement { get; set; }
        public string ExtraActivities { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
