//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonInfo()
        {
            this.GeneralDonarDetails = new HashSet<GeneralDonarDetail>();
            this.GeneralLoans = new HashSet<GeneralLoan>();
            this.Marriages = new HashSet<Marriage>();
            this.Marriages1 = new HashSet<Marriage>();
            this.MassMrgCommitties = new HashSet<MassMrgCommitty>();
            this.MassMrgDonarDetails = new HashSet<MassMrgDonarDetail>();
            this.MassMrgGifts = new HashSet<MassMrgGift>();
            this.MassMrgRegs = new HashSet<MassMrgReg>();
            this.MassMrgRegs1 = new HashSet<MassMrgReg>();
            this.PersonInfo1 = new HashSet<PersonInfo>();
            this.PersonInfo11 = new HashSet<PersonInfo>();
            this.StudentLoans = new HashSet<StudentLoan>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FamilyId { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string BirthPlace { get; set; }
        public string Education { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> FatherId { get; set; }
        public Nullable<int> MotherId { get; set; }
        public Nullable<byte> IsDead { get; set; }
        public string CurrentAddresss { get; set; }
        public Nullable<byte> IsMemberOfCommunityServiceCenter { get; set; }
        public Nullable<System.DateTime> DeathDate { get; set; }
        public Nullable<byte> IsMarried { get; set; }
        public string Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Photo { get; set; }
        public Nullable<int> SakhId { get; set; }
    
        public virtual FamilyInfo FamilyInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralDonarDetail> GeneralDonarDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralLoan> GeneralLoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marriage> Marriages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Marriage> Marriages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MassMrgCommitty> MassMrgCommitties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MassMrgDonarDetail> MassMrgDonarDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MassMrgGift> MassMrgGifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MassMrgReg> MassMrgRegs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MassMrgReg> MassMrgRegs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonInfo> PersonInfo1 { get; set; }
        public virtual PersonInfo PersonInfo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonInfo> PersonInfo11 { get; set; }
        public virtual PersonInfo PersonInfo3 { get; set; }
        public virtual Sakh Sakh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentLoan> StudentLoans { get; set; }
    }
}
