//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community
{
    using System;
    using System.Collections.Generic;
    
    public partial class VillageStatatic
    {
        public int Id { get; set; }
        public int VillageId { get; set; }
        public System.DateTime Date { get; set; }
        public string Detail { get; set; }
        public string History { get; set; }
    
        public virtual Village Village { get; set; }
    }
}
